spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: 44578368
  jpa:
    hibernate:
      ddl-auto: validate     # Flyway maneja el esquema
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

